SIZE = $(firstword $(subst x, ,$(notdir $(shell pwd))))
DIRS = apps devices places
ALL = \
	devices/adminvm-black.png \
	devices/appvm-red.png \
	devices/appvm-orange.png \
	devices/appvm-yellow.png \
	devices/appvm-green.png \
	devices/appvm-gray.png \
	devices/appvm-blue.png \
	devices/appvm-purple.png \
	devices/appvm-black.png \
	devices/appvm-brown.png \
	devices/appvm-cyan.png \
	devices/appvm-indigo.png \
	devices/appvm-lime.png \
	devices/appvm-pink.png \
	devices/appvm-white.png \
	devices/dispvm-red.png \
	devices/dispvm-orange.png \
	devices/dispvm-yellow.png \
	devices/dispvm-green.png \
	devices/dispvm-gray.png \
	devices/dispvm-blue.png \
	devices/dispvm-purple.png \
	devices/dispvm-black.png \
	devices/dispvm-brown.png \
	devices/dispvm-cyan.png \
	devices/dispvm-indigo.png \
	devices/dispvm-lime.png \
	devices/dispvm-pink.png \
	devices/dispvm-white.png \
	devices/templatevm-red.png \
	devices/templatevm-orange.png \
	devices/templatevm-yellow.png \
	devices/templatevm-green.png \
	devices/templatevm-gray.png \
	devices/templatevm-blue.png \
	devices/templatevm-purple.png \
	devices/templatevm-black.png \
	devices/templatevm-brown.png \
	devices/templatevm-cyan.png \
	devices/templatevm-indigo.png \
	devices/templatevm-lime.png \
	devices/templatevm-pink.png \
	devices/templatevm-white.png \
	devices/remotevm-red.png \
	devices/remotevm-orange.png \
	devices/remotevm-yellow.png \
	devices/remotevm-green.png \
	devices/remotevm-gray.png \
	devices/remotevm-blue.png \
	devices/remotevm-purple.png \
	devices/remotevm-black.png \
	devices/remotevm-brown.png \
	devices/remotevm-cyan.png \
	devices/remotevm-indigo.png \
	devices/remotevm-lime.png \
	devices/remotevm-pink.png \
	devices/remotevm-white.png \
	devices/servicevm-red.png \
	devices/servicevm-orange.png \
	devices/servicevm-yellow.png \
	devices/servicevm-green.png \
	devices/servicevm-gray.png \
	devices/servicevm-blue.png \
	devices/servicevm-purple.png \
	devices/servicevm-black.png \
	devices/servicevm-brown.png \
	devices/servicevm-cyan.png \
	devices/servicevm-indigo.png \
	devices/servicevm-lime.png \
	devices/servicevm-pink.png \
	devices/servicevm-white.png \

all: dirs $(ALL)
.PHONY: all

# some directories may be empty, so git won't check them out
dirs:
	mkdir -p $(DIRS)
.PHONY: dirs

devices/%-red.png:  NAME = red
devices/%-orange.png:	NAME = orange
devices/%-yellow.png:	NAME = yellow
devices/%-green.png:    NAME = green
devices/%-gray.png: NAME = gray
devices/%-blue.png: NAME = blue
devices/%-purple.png:	NAME = purple
devices/%-black.png:	NAME = black
devices/%-brown.png:	NAME = brown
devices/%-cyan.png:	NAME = cyan
devices/%-indigo.png:	NAME = indigo
devices/%-lime.png:	NAME = lime
devices/%-pink.png:	NAME = pink
devices/%-white.png:	NAME = white

devices/appvm-%.png: TYPE = appvm
devices/dispvm-%.png: TYPE = dispvm
devices/templatevm-%.png: TYPE = templatevm
devices/remotevm-%.png: TYPE = remotevm
devices/servicevm-%.png: TYPE = servicevm
devices/adminvm-%.png: TYPE = adminvm

devices/%.png:
ifeq ($(strip $(shell inkscape --version | grep -o 'Inkscape 0.')),Inkscape 0.)
	inkscape -z -w $(SIZE) -h $(SIZE)  ../scalable/apps/$(TYPE)-$(NAME).svg -e $@
else
	inkscape -w $(SIZE) -h $(SIZE) -o $@ ../scalable/apps/$(TYPE)-$(NAME).svg
endif


clean:
.PHONY: clean

MYDESTDIR = $(DESTDIR)/usr/share/icons/hicolor/$(notdir $(shell pwd))
install:
	install -d $(MYDESTDIR)
	for dir in $(DIRS); do \
		cp -r $$dir $(MYDESTDIR)/ || exit 1; \
	done
.PHONY: install
